###Ruta principal (Devuelve un mensaje de bienvenida a la API).
http://localhost:3000

###Devuelve todos los productos.
GET http://localhost:3000/productos

###Devuelve un producto por su ID. 
GET http://localhost:3000/productos/667b18294376c71e3f404f18

###Filtrar productos por nombre (búsqueda parcial).
GET http://localhost:3000/productos/nombre/d

###Agregar un nuevo producto.
POST http://localhost:3000/productos 
content-type: application/json

{
    "codigo": 28,
    "nombre": "Duriannnn",
    "precio": 10000,
    "categoria": "Fruta"
}