###Ruta principal (Devuelve un mensaje de bienvenida a la API).
http://localhost:3000

###Devuelve todos los productos.
GET http://localhost:3000/productos

###Devuelve un producto por su ID. 
GET http://localhost:3000/productos/667c5e57583157f264da0f0a

###Filtrar productos por nombre (búsqueda parcial).
GET http://localhost:3000/productos/nombre/d

###Agregar un nuevo producto.
POST http://localhost:3000/productos 
content-type: application/json

{
    "codigo": 55,
    "nombre": "Durian",
    "precio": 10000,
    "categoria": "Fruta"
}

###Modificar el precio de un producto (parcialmente).
PATCH http://localhost:3000/productos/667c5cb897c471bac156d16
content-type: application/json

{
    "codigo": 100,
    "precio": 44000
}